services:
  database:
    image: mariadb:13.0.2@sha256:d4fdec0510ad498e4f3127da30a99df3745bd6d5e611ae6ac5f76403d9284a8d
    ports:
      - "3306:3306"
    environment:
      MARIADB_USER: spring
      MARIADB_PASSWORD: test
      MARIADB_DATABASE: discordmodbot
      MARIADB_ROOT_PASSWORD: test
  redis:
    image: redis:8.10.2@sha256:d5ac52db24d4e70566fe9944f22cf5bdc2bc739b05c0f426335161ea6c23f3b3
    ports:
      - "6379:6379"
