logging.level.root=info
# Profile
spring.profiles.active=production
# H2
spring.h2.console.enabled=false
spring.h2.console.path=/h2
# Datasource
spring.datasource.url=jdbc:h2:file:./discordModBot;MODE=MySQL;DATABASE_TO_LOWER=TRUE
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver
# Hibernate
spring.jpa.hibernate.ddl-auto=none
# Modulith
spring.modulith.detection-strategy=explicitly-annotated
