name: Dependency Submission

on:
  push:
    branches:
      - main

jobs:
  Dependency_Submission:
    name: Dependency Submission
    runs-on: ubuntu-latest
    
    permissions: # The Dependency Submission API requires write permission
      contents: write

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Java JDK
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          java-version: 17
          distribution: liberica

      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@39e147cb9de83bb9910b8ef8bd7fff0ee20fcd6f # v6.0.1
        with:
          dependency-graph-include-configurations: 'RuntimeClasspath'
