name: Dependency Submission

on:
  push:
    branches:
      - main

jobs:
  Dependency_Submission:
    name: Dependency Submission
    runs-on: ubuntu-latest
    
    permissions: # The Dependency Submission API requires write permission
      contents: write

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup Java JDK
        uses: actions/setup-java@ad2b38190b15e4d6bdf0c97fb4fca8412226d287 # v5.3.0
        with:
          java-version: 17
          distribution: liberica

      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0
        with:
          dependency-graph-include-configurations: 'RuntimeClasspath'
