name: Test MariaDB

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    timeout-minutes: 30
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:12.2.2@sha256:b1cb255a9939d28a1856815f0de6046c20c28c21b92a9f2696bc782b247a47ee
        ports:
          - 3306:3306
        env:
          MARIADB_USER: spring
          MARIADB_PASSWORD: test
          MARIADB_DATABASE: discordmodbot
          MARIADB_ROOT_PASSWORD: test
        options: >-
          --health-cmd "/usr/local/bin/healthcheck.sh --su-mysql --connect --innodb_initialized"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Java JDK
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          java-version: 17
          distribution: liberica

      - name: Run Setup Gradle
        uses: gradle/actions/setup-gradle@0723195856401067f7a2779048b490ace7a47d7c # v5.0.2

      - name: Run Gradle check
        run: ./gradlew check
        env:
          SPRING_DATASOURCE_URL: jdbc:mariadb://127.0.0.1:3306/discordmodbot
          SPRING_DATASOURCE_USERNAME: spring
          SPRING_DATASOURCE_PASSWORD: test
          SPRING_DATASOURCE_DRIVERCLASSNAME: org.mariadb.jdbc.Driver
