name: Test MariaDB

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    timeout-minutes: 30
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:12.1.2@sha256:f54db0cb3ccfe9431aba6d08c65a1763c499789b116b4cb651dd7fcf325965b3
        ports:
          - 3306:3306
        env:
          MARIADB_USER: spring
          MARIADB_PASSWORD: test
          MARIADB_DATABASE: discordmodbot
          MARIADB_ROOT_PASSWORD: test
        options: >-
          --health-cmd "/usr/local/bin/healthcheck.sh --su-mysql --connect --innodb_initialized"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Setup Java JDK
        uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5.0.0
        with:
          java-version: 17
          distribution: liberica

      - name: Run Setup Gradle
        uses: gradle/actions/setup-gradle@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2 # v5.0.0

      - name: Run Gradle check
        run: ./gradlew check
        env:
          SPRING_DATASOURCE_URL: jdbc:mariadb://127.0.0.1:3306/discordmodbot
          SPRING_DATASOURCE_USERNAME: spring
          SPRING_DATASOURCE_PASSWORD: test
          SPRING_DATASOURCE_DRIVERCLASSNAME: org.mariadb.jdbc.Driver
