name: Test PostgreSQL

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    timeout-minutes: 30
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:18@sha256:4aabea78cf39b90e834caf3af7d602a18565f6fe2508705c8d01aa63245c2e20
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: spring
          POSTGRES_PASSWORD: test
          POSTGRES_DB: discordmodbot
        options: >-
          --health-cmd "pg_isready -U spring -d discordmodbot"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup Java JDK
        uses: actions/setup-java@1bcf9fb12cf4aa7d266a90ae39939e61372fe520 # v5.4.0
        with:
          java-version: 25
          distribution: liberica

      - name: Run Setup Gradle
        uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0

      - name: Run Gradle check
        run: ./gradlew check
        env:
          SPRING_PROFILES_ACTIVE: testing,postgresql
          SPRING_DATASOURCE_URL: jdbc:postgresql://127.0.0.1:5432/discordmodbot
          SPRING_DATASOURCE_USERNAME: spring
          SPRING_DATASOURCE_PASSWORD: test
          SPRING_DATASOURCE_DRIVERCLASSNAME: org.postgresql.Driver
          SPRING_FLYWAY_LOCATIONS: classpath:db/migration/postgresql
