name: 'Create pre-release'

on:
  push:
    branches:
      - main

permissions:
  contents: write  # Required for google-github-actions/release-please-action
  pull-requests: write # Required for google-github-actions/release-please-action

concurrency:
  group: ${{ github.workflow }}

jobs:
  release_please:
    name: "Run Release Please"
    runs-on: ubuntu-latest

    outputs:
      release_created: ${{ steps.release.outputs.release_created }}

    steps:
      - uses: google-github-actions/release-please-action@d3c71f9a0a55385580de793de58da057b3560862 # v3
        id: release
        with:
          release-type: java
          bootstrap-sha: '19b9ecc915c079bc292b9e2769bcd156657234da'
          prerelease: true
          extra-files: |
            version.txt
