name: Create release

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}

jobs:
  release_please:
    name: Run Release Please
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Required for google-github-actions/release-please-action
      pull-requests: write # Required for google-github-actions/release-please-action

    outputs:
      release_created: ${{ steps.release.outputs.release_created }}

    steps:
      - uses: google-github-actions/release-please-action@db8f2c60ee802b3748b512940dde88eabd7b7e01 # v3.7.13
        id: release
        with:
          release-type: java
          bootstrap-sha: 19b9ecc915c079bc292b9e2769bcd156657234da
          extra-files: build.gradle.kts
