name: Create release

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}

jobs:
  release_please:
    name: Run Release Please
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Required for google-github-actions/release-please-action
      pull-requests: write # Required for google-github-actions/release-please-action

    outputs:
      release_created: ${{ steps.release.outputs.release_created }}

    steps:
      - uses: google-github-actions/release-please-action@cc61a07e2da466bebbc19b3a7dd01d6aecb20d1e # v4.0.2
        id: release
