name: Create release

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}

jobs:
  release_please:
    name: Run Release Please
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Required for google-github-actions/release-please-action
      pull-requests: write # Required for google-github-actions/release-please-action

    outputs:
      release_created: ${{ steps.release.outputs.release_created }}

    steps:
      - uses: googleapis/release-please-action@16a9c90856f42705d54a6fda1823352bdc62cf38 # v4.4.0
        id: release
